package cm.g2s.loan.domain.event;

public enum LoanEvent {
    VALIDATE_LOAN, VALIDATE_LOAN_PASSED, VALIDATE_LOAN_FAILED,
    DEBIT_ACCOUNT, DEBIT_ACCOUNT_PASSED, DEBIT_ACCOUNT_FAILED,
    CREATE_TRANSACTION, CREATE_TRANSACTION_PASSED, CREATE_TRANSACTION_FAILED,
    SEND_TRANSACTION, SEND_TRANSACTION_PASSED, SEND_TRANSACTION_FAILED,
    CONFIRM_DEBIT, CONFIRM_DEBIT_PASSED, CONFIRM_DEBIT_FAILED,
    SEND_NOTIFICATION, SEND_NOTIFICATION_PASSED, SEND_NOTIFICATION_FAILED,
    TERMINATE
}
