package cm.g2s.loan.domain.event;

public enum LoanEvent {
    VALIDATE_LOAN, VALIDATE_LOAN_PASSED, VALIDATE_LOAN_FAILED,
    ACCOUNT_DEBIT, ACCOUNT_DEBIT_PASSED, ACCOUNT_DEBIT_FAILED,
    MONEY_SEND, MONEY_SEND_PASSED, MONEY_SEND_FAILED,
    CONFIRM_DEBIT, CONFIRM_DEBIT_PASSED, CONFIRM_DEBIT_FAILED,
    SEND_NOTIFICATION, SEND_NOTIFICATION_PASSED, SEND_NOTIFICATION_FAILED,
    TERMINATE
}
