version: '3.7'
services:
  dbpostgresql:
    image: "postgres:12.3-alpine"
    hostname: dbpostgresql
    container_name: dbpostgresql
    ports:
      - "5838:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=?.@159MmmmM@..!
      - POSTGRES_DB=postgres

  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: gmoneyrabbitmq
    container_name: gmoneyrabbitmq
    ports:
      - "5840:5672"
      - "15840:15672"
    volumes:
      - ./rabbitmq-definitions:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-config:/etc/rabbitmq/rabbitmq.config:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    ports:
      - "5839:80"
    volumes:
      - ./pgadmin-data:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=gomney@g2snet.com
      - PGADMIN_DEFAULT_PASSWORD=?.@159MmmmM@..!
  configuration:
    restart: always
    hostname: configuration
    container_name: configuration
    image: ambaindji/gmoney-configuration:latest
    build:
      context: configuration-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "7500:7500"
    environment:
      - PROFILE=test
  discovery:
    restart: always
    hostname: discovery
    container_name: discovery
    image: ambaindji/gmoney-discovery:latest
    build:
      context: discovery-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7010:7010"
      - "7510:7510"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
  proxy:
    restart: always
    hostname: proxy
    container_name: proxy
    image: ambaindji/gmoney-proxy:latest
    build:
      context: proxy-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "8500:8500"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - PROFILE=test
  account:
    restart: always
    hostname: account
    container_name: account
    image: ambaindji/gmoney-account:latest
    build:
      context: account-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8150:8150"
      - "8550:8550"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_account_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test

  company:
    restart: always
    hostname: company
    container_name: company
    image: ambaindji/gmoney-company:latest
    build:
      context: company-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8120:8120"
      - "8520:8520"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_company_db
      - PROFILE=test
  cron:
    restart: always
    hostname: cron
    container_name: cron
    image: ambaindji/gmoney-cron:latest
    build:
      context: cron-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8190:8190"
      - "8590:8590"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_cron_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  documentation:
    restart: always
    hostname: documentation
    container_name: documentation
    image: ambaindji/gmoney-documentation:latest
    build:
      context: documentation-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8140:8140"
      - "8540:8540"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - PROFILE=test
  loan:
    restart: always
    hostname: loan
    container_name: loan
    image: ambaindji/gmoney-loan:latest
    build:
      context: loan-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8170:8170"
      - "8570:8570"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_loan_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  momo:
    restart: always
    hostname: momo
    container_name: momo
    image: ambaindji/gmoney-momo:latest
    build:
      context: momo-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8210:8210"
      - "8610:8610"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - PROFILE=test
  notification:
    restart: always
    hostname: notification
    container_name: notification
    image: ambaindji/gmoney-notification:latest
    build:
      context: notification-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
      - "8600:8600"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_notification_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  partner:
    restart: always
    hostname: partner
    container_name: partner
    image: ambaindji/gmoney-partner:latest
    build:
      context: partner-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8130:8130"
      - "8530:8530"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_partner_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  rule:
    restart: always
    hostname: rule
    container_name: rule
    image: ambaindji/gmoney-rule:latest
    build:
      context: rule-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8160:8160"
      - "8560:8560"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_rule_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  transaction:
    restart: always
    hostname: transaction
    container_name: transaction
    image: ambaindji/gmoney-transaction:latest
    build:
      context: transaction-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
      - "8580:8580"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_transaction_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test
  uaa:
    restart: always
    hostname: uaa
    container_name: uaa
    image: ambaindji/gmoney-uaa:latest
    build:
      context: uaa-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8110:8110"
      - "8510:8510"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_uaa_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test

