version: '3.3'
services:
  dbpostgresql:
    image: postgres
    hostname: dbpostgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=?.@159MmmmM@++
      - POSTGRES_USER=gmoney
      - POSTGRES_DB=gmoney_account_db
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: gmoneyrabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-definitions:/etc/rabbitmq/definitions.json:ro
      - rabbitmq-config:/etc/rabbitmq/rabbitmq.config:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - "5858:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@g2snet.com
      - PGADMIN_DEFAULT_PASSWORD=?.@159MmmmM@++
  configuration:
    restart: always
    hostname: configuration
    container_name: configuration
    image: ambaindji/gmoney-configuration:latest
    build:
      context: configuration-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "7500:7500"
    environment:
      - PROFILE=test
  discovery:
    restart: always
    hostname: discovery
    container_name: discovery
    image: ambaindji/gmoney-discovery:latest
    build:
      context: discovery-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7010:7010"
      - "7510:7510"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
  proxy:
    restart: always
    hostname: proxy
    container_name: proxy
    image: ambaindji/gmoney-proxy:latest
    build:
      context: proxy-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "8500:8500"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - PROFILE=test
  account:
    restart: always
    hostname: account
    container_name: account
    image: ambaindji/gmoney-account:latest
    build:
      context: account-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8150:8150"
      - "8550:8550"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_DB=gmoney_account_db
      - RABBIT_MQ_HOST=gmoneyrabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER_NAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - PROFILE=test

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq-definitions:
  rabbitmq-config:

