version: '3'
services:
  configuration:
    restart: always
    hostname: configuration
    container_name: configuration
    image: gmoney/configuration:latest
    ports:
      - "7000:7000"
      - "7500:7500"
    environment:
      - PROFILE=test
  discovery:
    restart: always
    hostname: discovery
    container_name: discovery
    image: gmoney/discovery:latest
    ports:
      - "7000:7000"
      - "7510:7510"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
  proxy:
    restart: always
    hostname: proxy
    container_name: proxy
    image: gomney/proxy:latest
    ports:
      - "5000:5000"
      - "5500:5500"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
      - DISCOVERY_SERVICE=http://discovery:7010/eureka

