version: '3.3'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=?.@159MmmmM@++
      - POSTGRES_USER=gmoney
      - POSTGRES_DB=gmoney_account_db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5858:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@g2snet.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/root/.pgadmin

  configuration:
    restart: always
    hostname: configuration
    container_name: configuration
    image: ambaindji/gmoney-configuration:latest
    build:
      context: configuration-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "7500:7500"
    environment:
      - PROFILE=test
  discovery:
    restart: always
    hostname: discovery
    container_name: discovery
    image: ambaindji/gmoney-discovery:latest
    build:
      context: discovery-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "7510:7510"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
  proxy:
    restart: always
    hostname: proxy
    container_name: proxy
    image: ambaindji/gmoney-proxy:latest
    build:
      context: proxy-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "8500:8500"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
      - DISCOVERY_SERVICE=http://discovery:7010/eureka
  account:
    restart: always
    hostname: account
    container_name: account
    image: ambaindji/gmoney-account:latest
    build:
      context: account-service/src/main/docker
      dockerfile: Dockerfile
    ports:
      - "8150:8150"
      - "8550:8550"
    environment:
      - CONFIGURATION_SERVICE=http://configuration:7000
      - PROFILE=test
      - DISCOVERY_SERVICE=http://discovery:7010/eureka

volumes:
  - pgadmin-data
  - postgres-data
