spring:
  cloud:
    config:
      server:
        git:
          search-paths: '{application}'
          cloneOnStart: true
server:
  port: 7000
  servlet:
    context-path: /config
management:
  server:
    port: 7500
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always