package cm.g2s.uaa.domain.model;

public enum UserState {
    NEW,
    PARTNER_CREATED_PENDING, PARTNER_CREATED, PARTNER_CREATED_EXCEPTION,
    ACCOUNT_CREATED_PENDING, ACCOUNT_CREATED, ACCOUNT_CREATED_EXCEPTION,
    USER_CREATED

}
