package cm.g2s.loan.domain.model;

public enum LoanState {
    DRAFT,
    VALID_PENDING, VALID, VALID_EXCEPTION,
    ACCOUNT_DEBIT_PENDING, ACCOUNT_DEBIT, ACCOUNT_DEBIT_EXCEPTION,
    MONEY_SEND_PENDING, MONEY_SEND, MONEY_SEND_EXCEPTION,
    CONFIRM_DEBIT_PENDING, CONFIRM_DEBIT, CONFIRM_DEBIT_EXCEPTION,
    NOTIFICATION_SEND_PENDING, NOTIFICATION_SEND, NOTIFICATION_EXCEPTION,
    DONE;

}
