package cm.g2s.loan.domain.model;

public enum LoanState {
    DRAFT,
    VALID_PENDING, VALID, VALID_EXCEPTION,
    ACCOUNT_DEBIT_PENDING, ACCOUNT_DEBIT, ACCOUNT_DEBIT_EXCEPTION,
    TRANSACTION_CREATED_PENDING, TRANSACTION_CREATED, TRANSACTION_CREATED_EXCEPTION,
    TRANSACTION_SEND_PENDING, TRANSACTION_SEND, TRANSACTION_SEND_EXCEPTION,
    CONFIRM_DEBIT_PENDING, CONFIRM_DEBIT, CONFIRM_DEBIT_EXCEPTION,
    EMAIL_NOTIFICATION_CREATE_PENDING, EMAIL_NOTIFICATION_CREATE, EMAIL_NOTIFICATION_CREATE_EXCEPTION,
    DONE;

}
