package cm.g2s.uaa.domain.event;

public enum UserEvent {
    CREATE_PARTNER, CREATE_PARTNER_PASSED, CREATE_PARTNER_FAILED,
    CREATE_ACCOUNT, CREATE_ACCOUNT_PASSED,  CREATED_ACCOUNT_FAILED,
    CREATE_USER
}
